### ISSUE TITLE
Implement new Kover DSL with project isolation support 

### ISSUE THREAD

**Issue by shanshin** [Kotlin/kotlinx-kover#284]
- [x]  design new DSL
- [x] implement DSL
- [x] implement project isolation (#144, #221)
- [x] write tests on project isolation
- [x] rewrite existed tests to new API
- [x] extract API of coverage tools (#195)
- [x] support Android build variant (#18)
- [x] support filtering by source sets (#245)

**Comment by shanshin** [comment]
Resolved in `0.7.0-Alpha`
